# Generated by Django 5.0.6 on 2024-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('size_type', models.CharField(max_length=25)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('colour', models.CharField(max_length=24)),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
